- hosts: server
  become: yes
  vars:
    - homejs: /home/foundry/foundryuser/resources/app/main.js
    - pm2: /usr/local/bin/pm2
    - link: https://foundryvtt.s3.amazonaws.com/releases/11.301/FoundryVTT-11.301.zip?AWSAccessKeyId=AKIA2KJE5YZ3BCQQ6DH3&Signature=okTUwSHnzAwVRigd7ghmP70Y%2BW4%3D&Expires=1686838105
  tasks:
    - name: Instalando Pacotes
      package:
        name: 
        - openssl-devel
        - nodejs
        state: present
    
    - name: Instalando PM2 (NPM)
      community.general.npm:
        name: pm2@latest
        global: true
        state: present
    
    - name: Baixando Foundry
      shell: | 
        mkdir -p /home/foundry/foundryuserdata
        mkdir -p /home/foundry/foundryuser
        wget --output-document /home/foundry/foundryvtt.zip "{{link}}"
      tags:
        - download

    - name: Instalando Foundry
      unarchive: 
        src: /home/foundry/foundryvtt.zip
        dest: /home/foundry/foundryuser/
        remote_src: yes
      tags:
        - install

    - name: Iniciando PM2
    shell: |
         {{pm2}} start "node {{homejs}}" --name foundry
      tags:
        - start

    
  

